# Build Nixery, spin up an instance and pull an image from it.
name: "Build and test Nixery"
on:
  push:
    branches:
      - master
  pull_request: {}
env:
  NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/4263ba5e133cc3fc699c1152ab5ee46ef668e675.tar.gz"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v13
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Prepare environment
        run: nix-env -f '<nixpkgs>' -iA go
      - name: Check formatting
        run: "test -z $(gofmt -l .)"
      - name: Build Nixery
        run: "nix-build --arg maxLayers 2 --no-out-link"
      - name: Run integration test
        run: scripts/integration-test.sh
